### ISSUE TITLE
HTML 500 error with ResourceLoader startup module

### ISSUE THREAD

**Issue by alistair3149** [jdlrobson/skins.wmflabs.org#17]
**Describe the bug**
ResourceLoader startup module returns a HTML 500 error, which prevent all the JS in startup module from loading.
Reproducible with multiple configurations, including pages, skins, browsers, OS.
The error seems to stem from Minerva, see attached log below:
```
[0cdcd03f76f7dedb4483f064] /w/load.php?lang=en&modules=startup&only=scripts&raw=1&skin=citizen TypeError: Argument 2 passed to MediaWiki\Minerva\Hooks::onPreferencesGetLayout() must be an instance of Skin, string given, called in /vagrant/mediawiki/includes/HookContainer/HookContainer.php on line 160

Backtrace:

from /vagrant/mediawiki/skins/MinervaNeue/includes/Hooks.php(108)
#0 /vagrant/mediawiki/includes/HookContainer/HookContainer.php(160): MediaWiki\Minerva\Hooks::onPreferencesGetLayout()
#1 /vagrant/mediawiki/includes/HookContainer/HookRunner.php(3113): MediaWiki\HookContainer\HookContainer->run()
#2 /vagrant/mediawiki/resources/Resources.php(2303): MediaWiki\HookContainer\HookRunner->onPreferencesGetLayout()
#3 /vagrant/mediawiki/includes/ResourceLoader/FileModule.php(1265): Wikimedia\Services\ServiceContainer::{closure}()
#4 /vagrant/mediawiki/includes/ResourceLoader/FileModule.php(608): MediaWiki\ResourceLoader\FileModule->expandPackageFiles()
#5 /vagrant/mediawiki/includes/ResourceLoader/Module.php(931): MediaWiki\ResourceLoader\FileModule->getDefinitionSummary()
#6 /vagrant/mediawiki/includes/ResourceLoader/StartUpModule.php(224): MediaWiki\ResourceLoader\Module->getVersionHash()
#7 /vagrant/mediawiki/includes/ResourceLoader/StartUpModule.php(425): MediaWiki\ResourceLoader\StartUpModule->getModuleRegistrations()
#8 /vagrant/mediawiki/includes/ResourceLoader/Module.php(817): MediaWiki\ResourceLoader\StartUpModule->getScript()
#9 /vagrant/mediawiki/includes/ResourceLoader/Module.php(786): MediaWiki\ResourceLoader\Module->buildContent()
#10 /vagrant/mediawiki/includes/ResourceLoader/Module.php(928): MediaWiki\ResourceLoader\Module->getModuleContent()
#11 /vagrant/mediawiki/includes/ResourceLoader/ResourceLoader.php(692): MediaWiki\ResourceLoader\Module->getVersionHash()
#12 [internal function]: MediaWiki\ResourceLoader\ResourceLoader->MediaWiki\ResourceLoader\{closure}()
#13 /vagrant/mediawiki/includes/ResourceLoader/ResourceLoader.php(690): array_map()
#14 /vagrant/mediawiki/includes/ResourceLoader/ResourceLoader.php(789): MediaWiki\ResourceLoader\ResourceLoader->getCombinedVersion()
#15 /vagrant/mediawiki/load.php(53): MediaWiki\ResourceLoader\ResourceLoader->respond()
#16 /vagrant/mediawiki/load.php(39): wfLoadMain()
#17 /var/www/w/load.php(5): require(string)
#18 {main}
```

**To Reproduce**
1. Load any page on skin-demo

**Expected behavior**
Startup module should be loaded normally.

**Comment by jdlrobson** [comment]
Should be fixed now! Sorry about that!
